---
stages:
- name: Build
  inputs:
  - service: ${REPO}
    type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    working_dir: StoreWebApp
    artifact_dir: ''
    build_type: npm
    script: |-
      #!/bin/bash
      npm install
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  properties:
  - name: APP_DOMAIN
    value: ${DOMAIN}
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: "ibm:yp:us-south"
      organization: "simon_kaegi@ca.ibm.com"
      space: "dev"
      application: "bluecompute-web-tc"
    script: |-
      #!/bin/bash
      cf push "${CF_APP}" -n "${CF_APP}" -d "${APP_DOMAIN}"
