---
stages:
- name: Build
  inputs:
  - service: ${REPO}
    type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    working_dir: StoreWebApp
    artifact_dir: ''
    build_type: npm
    script: |-
      #!/bin/bash
      npm install
